Completed es6-classes
K-Bowler/m3-0822-code-solutions pull request #4
Opened 2022-08-24 04:08 UTC by K-Bowler

![image](https://user-images.githubusercontent.com/43438792/186326724-ef435dd4-0834-4fc8-94db-e90395b3f026.png)
![image](https://user-images.githubusercontent.com/43438792/186326739-512f576a-7d22-4d6f-9a59-4ba0fd0408f1.png)
![image](https://user-images.githubusercontent.com/43438792/186326760-a3dfd7e6-22e5-4d64-806e-4eb5a4cdf31d.png)

2022-08-24 04:19 UTC, scbowler requested changes
A few updates needed, let me know if you have any questions.

2022-08-24 04:19 UTC, scbowler commented on es6-classes/example-class.js
> +}
The `ExampleClass` should be an empty class:

```JAVASCRIPT
class ExampleClass {

};
```

2022-08-24 04:19 UTC, scbowler commented on es6-classes/stopwatch.js
> +};
With classes we don't need to prototype the methods on, they get defined inside the class.

```JAVASCRIPT
class SomeClass {
  constructor() {

  }

  aMethod() {

  }

  bMethod() {

  }

  cMethod() {

  }
}
```

2022-08-24 04:19 UTC, scbowler commented on es6-classes/student.js
> +};
Same here, the methods should be defined within the class

2022-08-24 16:02 UTC, scbowler requested changes
`Student` class looks good, but looks like you missed the changes for the `Stopwatch` and `ExampleClass` classes.

2022-08-26 01:33 UTC, K-Bowler commented
![image](https://user-images.githubusercontent.com/43438792/186797488-cefefc61-f766-49f0-a19a-466b49095249.png)

2022-08-26 02:19 UTC, scbowler approved these changes
Great job implementing ALL of the feedback, looks good! 👍

2022-08-26 02:19 UTC, merged